# Generated by Django 3.2.18 on 2023-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodtype',
            field=models.CharField(choices=[('a', 'A型'), ('b', 'B型'), ('o', 'O型'), ('ab', 'AB型'), ('etc', '不明')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'その他')]),
        ),
    ]
